######################################################################
# Automatically generated by qmake (3.0) Sun Apr 27 12:43:11 2014
######################################################################

TEMPLATE = app
TARGET = qconread
INCLUDEPATH += .
CONFIG += c++11
QT += widgets

# Input
HEADERS += qcreadwin.h logtableview.h logtablemodel.h
SOURCES += qcreadwin.cpp logtableview.cpp logtablemodel.cpp main.cpp
